INSERT INTO VIDEOJUEGO VALUES(0,"Spider-Man Miles Morales","Insomniac Games",59.99,"Asiste al acenso de Miles Morales a medida que el nuevo héroe controla sus increíbles y explosivos poderes para convertirse en su propio Spider-Man. En esta nueva aventura del universo de Marvel’s Spider-Man, el adolescente Miles Morales se va haciendo a su nuevo hogar mientras sigue los pasos de su mentor Peter Parker como el nuevo Spider-Man. Sin embargo, una encarnizada lucha destruye su nuevo hogar, tras lo que el héroe en ciernes descubre que un gran poder conlleva una gran responsabilidad. Para salvar la Nueva York de Marvel, Miles deberá heredar el traje de Spider-Man y hacerlo suyo.","Accion, Aventura","PS4, PS5",'20/11/12');
INSERT INTO VIDEOJUEGO VALUES(1,"Horizon Zero Dawn","Guerrilla Games",19.99,"Repudiada por su tribu al nacer, Aloy ha pasado toda su vida buscando respuestas a antiguos secretos y preguntas prohibidas. En una época en la que la humanidad ya no es la especie dominante y seres mecánicos con forma animal nos han arrebatado el control, la joven cazadora se embarcará en un viaje a través de un gigantesco mundo abierto post-apocalíptico para descubrir por qué la Tierra ya no nos pertenece. Horizon Zero Dawn, el nuevo y ambicioso proyecto de los veteranos Guerrilla, llega a PlayStation 4 retrocediendo la evolución humana hasta una nueva era de tribus de cazadores y recolectores en un juego de acción y rol con intensos combates estratégicos en los que ninguna especie de animal robótico se comportará igual que otra.","Accion, Aventura","PS4, PS5",'28/02/17');
INSERT INTO VIDEOJUEGO VALUES(2,"God of War","SCE Santa Monica Studio",19.99,"Adéntrate en una aventura compleja y desconocida en la que explorarás una impresionante versión alternativa de una historia clásica. Únete a Kratos en un profundo viaje de reflexión, crecimiento, violencia y el deseo de convertirse en un hombre mejor por su hijo. En un mundo de monstruos, dragones y dioses, el peso de la responsabilidad recae sobre tus hombros. Y cuando tu vida está marcada por la sangre y el caos, ¿cómo puedes evitar los errores del pasado para proteger tu futuro?","Accion, Aventura","PS4, PS5",'18/4/20');
INSERT INTO VIDEOJUEGO VALUES(3,"CyberPunk2077","CD Projekt",59.99,"Cyberpunk 2077 es una historia de acción y aventura en mundo abierto ambientada en Night City, una megalópolis obsesionada con el poder, el glamur y la modificación corporal. Tu personaje es V, un mercenario que persigue un implante único que permite alcanzar la inmortalidad. Podrás personalizar las mejoras cibernéticas, las habilidades y el estilo de juego del personaje para dar forma a un mundo y a una historia que depende de tus decisiones.","Accion, Aventura","PS4, PS5, XBOX ONE, XBOX SERIES X, PC",'20/12/10');
INSERT INTO VIDEOJUEGO VALUES(4,"Assassins Creed Valhalla","Ubisoft",59.99,"En Assassin's Creed Valhalla para PlayStation 4, PlayStation 5 y Xbox One compatible con Xbox One Series X, encarnarás a Eivor, una feroz leyenda vikinga criada entre historias de batallas y gloria. Explora un hermoso mundo abierto y cambiante ambientado en la despiadada Inglaterra de los años oscuros. Saquea a tus enemigos, haz prosperar tu asentamiento y consolida tu poder político mientras luchas por ganarte un sitio entre los dioses en el Valhalla.","Accion, Aventura","PS4, PS5, XBOX ONE, XBOX SERIES X",'20/11/10');
INSERT INTO VIDEOJUEGO VALUES(5,"Death Stranding","Kojima Productions",59.99,"Embárcate en un viaje como nunca antes has visto de la mano del legendario creador Hideo Kojima con Death Stranding para PlayStation 4. Como Sam Porter Bridges, deberéis salvar las diferencias en la sociedad y, al hacerlo, crear nuevos lazos o strands con otros jugadores de todo el mundo. A través de vuestra propia experiencia en el juego.","Accion, Aventura","PS4, PS5",'19/11/08');

INSERT INTO EMPLEADO VALUES("71163117M","Luis","Corzo Pereira",693472335,"luiscorzo@gmail.com","luiscorzo");

INSERT INTO CLIENTE VALUES("78965441H","Ramon","Martin Martin",698563214,"ramonmartin@gmail.com","ramonmartin");

